[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#5F6B45"
backgroundColor = "#E6E2D6"
secondaryBackgroundColor = "#D8D2C2"
textColor = "#1A1814"
font = "serif"
